/**
 * Curated emoji catalog for the picker. Each entry is [emoji, keywords].
 * Keywords are matched as substrings against the user's query so "thumb"
 * finds 👍 and "fire" finds 🔥. The first 8 also serve as the always-visible
 * frequent set when the search is empty.
 */
export const EMOJI_CATALOG: [string, string][] = [
  ["👍", "thumbs up yes ok approve"],
  ["❤️", "heart love"],
  ["😂", "laugh joy lol cry"],
  ["🎉", "party celebrate tada"],
  ["🔥", "fire lit hot"],
  ["👀", "eyes look watch see"],
  ["😢", "sad cry tear"],
  ["🙏", "pray thanks please"],
  ["👎", "thumbs down no nope"],
  ["✅", "check yes done correct"],
  ["❌", "x cross no wrong"],
  ["💯", "100 perfect score"],
  ["🤔", "think thinking hmm"],
  ["😅", "sweat smile awkward"],
  ["😎", "cool sunglasses"],
  ["😭", "crying sob bawl"],
  ["😡", "angry mad rage"],
  ["🤯", "mind blown shocked"],
  ["🥳", "party celebrate happy"],
  ["🤝", "handshake deal agree"],
  ["💪", "muscle strong flex"],
  ["👏", "clap applause bravo"],
  ["🙌", "raised hands praise"],
  ["✨", "sparkle shiny stars"],
  ["⭐", "star favorite"],
  ["💡", "idea bulb"],
  ["⚡", "lightning fast bolt"],
  ["🐛", "bug insect"],
  ["🚀", "rocket launch ship"],
  ["🎯", "target dart bullseye"],
  ["💀", "skull dead rip"],
  ["👻", "ghost spooky"],
  ["🤖", "robot bot"],
  ["☕", "coffee mug"],
  ["🍕", "pizza"],
  ["🍔", "burger food"],
  ["🍺", "beer drink"],
  ["🍰", "cake birthday"],
  ["🌮", "taco food"],
  ["🎵", "music note song"],
  ["🎮", "game controller play"],
  ["📺", "tv television"],
  ["💻", "laptop computer"],
  ["📱", "phone mobile"],
  ["⌨️", "keyboard"],
  ["🖱️", "mouse"],
  ["🐶", "dog puppy"],
  ["🐱", "cat kitten"],
  ["🦊", "fox"],
  ["🦁", "lion"],
  ["🐧", "penguin"],
  ["🦄", "unicorn magic"],
  ["🐢", "turtle slow"],
  ["🌈", "rainbow"],
  ["☀️", "sun sunny day"],
  ["🌙", "moon night"],
  ["🌧️", "rain"],
  ["❄️", "snow snowflake winter"],
  ["🌊", "wave water ocean"],
  ["🌍", "earth world globe"],
  ["💚", "green heart"],
  ["💙", "blue heart"],
  ["💜", "purple heart"],
  ["🖤", "black heart"],
  ["💛", "yellow heart"],
  ["💔", "broken heart sad"],
  ["💕", "two hearts love"],
  ["😀", "grin smile"],
  ["😊", "smile happy"],
  ["😉", "wink"],
  ["😌", "relieved calm"],
  ["😘", "kiss"],
  ["😏", "smirk smug"],
  ["😴", "sleep zzz tired"],
  ["🤐", "zip mouth shut"],
  ["🤫", "shush quiet"],
  ["🤣", "rofl laugh"],
  ["😬", "grimace awkward"],
  ["🙃", "upside down silly"],
  ["😱", "scream shock fear"],
  ["😳", "flushed embarrassed"],
  ["🥺", "pleading puppy eyes"],
  ["😷", "mask sick"],
  ["🤒", "thermometer sick fever"],
  ["🥵", "hot heat sweat"],
  ["🥶", "cold freeze"],
  ["😈", "devil mischief"],
  ["💩", "poop"],
  ["🎂", "cake birthday"],
  ["🎁", "gift present"],
  ["🏆", "trophy win"],
  ["🥇", "gold medal first"],
  ["💎", "diamond gem"],
  ["💰", "money cash bag"],
  ["📈", "chart up growth"],
  ["📉", "chart down decline"],
  ["🔔", "bell notification"],
  ["🔒", "lock secure"],
  ["🔑", "key"],
  ["🛠️", "tools wrench fix"],
  ["📌", "pin"],
  ["📎", "paperclip attach"],
  ["📝", "memo write note"],
  ["📚", "books read"],
  ["🎓", "graduation cap"],
  ["🌟", "glowing star"],
  ["🐝", "bee"],
  ["🦋", "butterfly"],
  ["🍎", "apple"],
  ["🍌", "banana"],
  ["🍇", "grapes"],
  ["🥑", "avocado"],
  ["🥦", "broccoli"],
  ["🍿", "popcorn"],
  ["🧀", "cheese"],
  ["🍩", "donut"],
  ["🍪", "cookie"],
  ["🍷", "wine"],
  ["🥤", "soda drink"],
];

export const QUICK_REACTIONS = EMOJI_CATALOG.slice(0, 8).map(([e]) => e);
