// Cross-language vectors for the prefs-blob key derivation and decryption,
// generated by directly invoking wavvon_identity::MasterIdentity and
// wavvon-desktop's prefs_blob.rs logic (HKDF-SHA256 + AES-256-GCM) for the
// same fixed entropy used elsewhere in this package's wire vectors
// (0x01..0x20). No vector for this exists yet in docs/wire-format.md; these
// pin derivePrefsBlobKey/decryptPrefsBlob to the exact bytes the desktop
// Tauri shell produces.
import { describe, it, expect } from "vitest";
import { masterSeedHex, derivePrefsBlobKey, decryptPrefsBlob } from "./master";
import { bytesToHex } from "../hex";

const ENTROPY_HEX = Array.from({ length: 32 }, (_, i) => (i + 1).toString(16).padStart(2, "0")).join("");

const MASTER_SEED_HEX = "5a5d527b13bccb7a21160cbe6d433b0c59e2793f27df43b74759da500b3b78c0";
const BLOB_KEY_HEX = "1b9b7050c27e40bccaef1efec2981dfc4b676093619782655a5427c1d08eaedd";
const BLOB_CIPHERTEXT_HEX =
  "00000000000000000000000065338dfb57de69d2d7dee5cbd93fefba9e93f9e4f966cf6909f30bd96b29b6ee9b597cc02040ccfab8729f3cc8a3d906c91007fb07cbbf2660413dfc7256156cf27e73b271f16acf6b8ce6472e28141800ecdc62";

describe("derivePrefsBlobKey", () => {
  it("matches wavvon-desktop's derive_blob_key for a fixed master seed", () => {
    expect(masterSeedHex(ENTROPY_HEX)).toBe(MASTER_SEED_HEX);
    expect(bytesToHex(derivePrefsBlobKey(MASTER_SEED_HEX))).toBe(BLOB_KEY_HEX);
  });
});

describe("decryptPrefsBlob", () => {
  it("decrypts a ciphertext produced by wavvon-desktop's encrypt_prefs", () => {
    const key = derivePrefsBlobKey(MASTER_SEED_HEX);
    const prefs = decryptPrefsBlob(BLOB_CIPHERTEXT_HEX, key);
    expect(prefs).toEqual({
      blocked_users: ["abc123"],
      voice_settings: { vad_threshold: 0.05 },
    });
  });

  it("rejects a truncated ciphertext", () => {
    const key = derivePrefsBlobKey(MASTER_SEED_HEX);
    expect(() => decryptPrefsBlob("00", key)).toThrow();
  });
});
